### ISSUE TITLE
New ccxt naming conventions

### ISSUE THREAD

**Issue by gabriel-lau** [nickpagz/3commas-ftx-triggers#12]
HI, I just came across this project and thought it was pretty cool. I noticed that bot creation through Py3c_create.py is not working anymore likely because of a new CCXT naming convention [here](https://github.com/ccxt/ccxt/issues/10931).

**Comment by nickpagz** [comment]
@gabriel-lau Thanks for linking to this. I knew they made breaking changes but missed that announcement. It's fixed for the newer script, and hopefully I'll get this fixed in the near future as well. For now, I think version 1.63.1 or sooner should still work.
