### ISSUE TITLE
Max bot usage wrong with leverage > 1

### ISSUE THREAD

**Issue by NobbisCrypto** [nickpagz/3commas-ftx-triggers#8]
Hi,

When I'm using 1x leverage the calculated max bot usage is correct. When I set it to 3 it's wrong.

My settings:
```
UPDATE_BASE_ORDER_VOLUME = 33 #IN USD
UPDATE_TAKE_PROFIT = 1.25
UPDATE_SAFETY_ORDER_VOLUME = 60
UPDATE_MARTINGALE_VOLUME_COEFFICIENT = 1.2
UPDATE_MARTINGALE_STEP_COEFFICIENT = 1.1
UPDATE_MAX_SAFETY_ORERS = 10
UPDATE_ACTIVE_SAFETY_ORDERS_COUNT = 3
UPDATE_SAFETY_ORDER_STEP_PERCENTAGE = 2.0
UPDATE_LEVERAGE_CUSTOM_VALUE = 3
UPDATE_STOP_LOSS_TYPE = 'stop_loss'  # or stop_loss_and_disable_bot
UPDATE_STOP_LOSS_PERCENTAGE = 0
UPDATE_STOP_LOSS_TIMEOUT_ENABLED = False
UPDATE_STOP_LOSS_TIMEOUT_IN_SECONDS = 300
UPDATE_START_ORDER_TYPE = 'market'
```

3commas calculation:
![image](https://user-images.githubusercontent.com/90933537/134311698-d21903b9-141e-4bf5-af1b-1a800a418e94.png)

Your calculation:
![image](https://user-images.githubusercontent.com/90933537/134311796-17d3a5ef-5c9a-475b-9f5a-8f069fa8a048.png)

**Comment by nickpagz** [comment]
@NobbisCrypto Nice catch! I haven't used the bot with leverage before, so didn't pick up on this error. I've marked it as a bug to fix. Thanks!

**Comment by NobbisCrypto** [comment]
I think you need to divide by the leverage factor `config.LEVERAGE_CUSTOM_VALUE` in the function `get_max_bot_usage` in `Py3c_triggers.py`.

Example: Your BO is 10 and SO is 20 with 1x leverage. You want to use 3x leverage, hence you set it to 3 and increase the BO to 30 and the SO to 60. That triples the amount for bot usage in your calculation - if you devide it by 3 your back to normal.

**Comment by nickpagz** [comment]
Yeah, exactly that.
